import './global.css';
import { Toaster } from '@writeme/wmc/lib/ui/toaster';
import { Toaster as Sonner } from '@writeme/wmc/lib/ui/sonner';
import { ThemeProvider } from '../components/theme-provider';
import SessionWrapper from '../components/session-provider';
import { ViewTransitions } from 'next-view-transitions';
import { Onborda, OnbordaProvider, Step } from 'onborda';
import { HandIcon } from 'lucide-react';
import { undefined } from 'zod';

export const metadata = {
  title: 'Welcome to writeme',
  description: 'Generated by create-nx-workspace'
};











export default function RootLayout({
                                     children
                                   }: {
  children: React.ReactNode;
}) {


  const steps = [
    {
      icon: <>👋</>,
      title: "Step 1",
      content: "Here you can create your first story",
      selector: '#new-my-works',
      nextRoute: '/myworks/new',
      pointerPadding: 10,
      pointerRadius: 10,
      prevRoute: undefined,
      showControls: true,
      side: "bottom"
    },
    {
      icon: <HandIcon></HandIcon>,
      title: "Step 2",
      content: "Give your Story a title...",
      selector: '#onborda-new-story-title',
      nextRoute: undefined,
      pointerPadding: 10,
      pointerRadius: 10,
      prevRoute: "/myworks",
      showControls: true,
      side: "right"
    },
    {
      icon: <HandIcon></HandIcon>,
      title: "Step 3",
      content: "Click Create",
      selector: '#onborda-new-story-create',
      nextRoute: undefined,
      pointerPadding: 10,
      pointerRadius: 10,
      prevRoute: undefined,
      showControls: true,
      side: "right"
    },
  ] satisfies Step[];
  return (
    <ViewTransitions>
      <html lang="en">
      <body>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
      >
        <SessionWrapper>
          <OnbordaProvider>
            <Onborda steps={steps} showOnborda={true}>
              {children}
            </Onborda>
          </OnbordaProvider>
          <Toaster></Toaster>
          <Sonner></Sonner>
        </SessionWrapper>
      </ThemeProvider>
      </body>
      </html>
    </ViewTransitions>
  );
}
