
import './global.css';
import { Toaster } from '@writeme/wmc/lib/ui/toaster';
import { Toaster as Sonner} from "@writeme/wmc/lib/ui/sonner";
import { ThemeProvider } from "../components/theme-provider"
export const metadata = {
  title: 'Welcome to writeme',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
      >
        {children}
        <Toaster></Toaster>
        <Sonner></Sonner>
      </ThemeProvider>
      </body>
    </html>
  );
}
