function slugify(str: String) {
  return String(str)
    .normalize('NFKD') // split accented characters into their base characters and diacritical marks
    .replace(/[\u0300-\u036f]/g, '') // remove all the accents, which happen to be all in the \u03xx UNICODE block.
    .trim() // trim leading or trailing whitespace
    .toLowerCase() // convert to lowercase
    .replace(/[^a-z0-9 -]/g, '') // remove non-alphanumeric characters
    .replace(/\s+/g, '-') // replace spaces with hyphens
    .replace(/-+/g, '-'); // remove consecutive hyphens
}

import 'dotenv/config';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { genres } from './schema';

export const connection = postgres(
  'postgres://username:password@localhost:5432/database',
  {
    host: process.env.DB_HOST?.trimEnd(),
    user: process.env.DB_USER?.trimEnd(),
    password: process.env.DB_PASSWORD?.trimEnd(),
    database: process.env.DB_NAME?.trimEnd(),
    port: parseInt(process.env.DB_PORT?.trimEnd() || '5432'),
    max: 1,
  }
);

let initial_genres = [
  'Speculative fiction',
  'Time travel',
  'Travel',
  'Non-fiction',
  'Morality play',
  'Travel literature',
  'First-person narrative',
  'Indian chick lit',
  'Literary realism',
  'Ergodic literature',
  'Serial',
  'Fairy tale',
  'Roman à clef',
  'Campus novel',
  'Social science fiction',
  'Gamebook',
  'Economics',
  'Vampire fiction',
  'Adventure',
  'Gothic fiction',
  'Cabal',
  'Post-holocaust',
  'Political philosophy',
  'Novel',
  'Picaresque novel',
  'Modernism',
  'Albino bias',
  'Transgender and transsexual fiction',
  'Neuroscience',
  'Dystopia',
  'Zombies in popular culture',
  'Feminist science fiction',
  'Experimental literature',
  'Space western',
  'Fantasy',
  'Religion',
  'Heroic fantasy',
  "Children's literature",
  'Philosophy',
  'Transhumanism',
  'Foreign legion',
  'Colonial United States romance',
  'Zombie',
  'Military science fiction',
  'Crime Fiction',
  'Fable',
  'New York Times Best Seller list',
  'Comedy of manners',
  'Epic Science Fiction and Fantasy',
  'Alternate history',
  'Literary fiction',
  'Sword and sorcery',
  'Scientific romance',
  'Georgian romance',
  'Wuxia',
  'Comic book',
  'New Weird',
  'Mashup',
  'Creative nonfiction',
  'Collage',
  'Literary theory',
  'Reference',
  'Politics',
  'Gay Themed',
  'Edisonade',
  'Fairytale fantasy',
  'Spirituality',
  'Catastrophic literature',
  'Social criticism',
  'Soft science fiction',
  'Human extinction',
  'Polemic',
  'Business',
  'Spy fiction',
  'Bit Lit',
  'Whodunit',
  'Invasion literature',
  'Bangsian fantasy',
  'Apocalyptic and post-apocalyptic fiction',
  'Encyclopedia',
  'Regency romance',
  'Military history',
  'Historical whodunnit',
  'Historical fantasy',
  'Coming of age',
  'Bildungsroman',
  'Fantasy of manners',
  'Drama',
  'Comics',
  'Anthropology',
  'Historical novel',
  'Picture book',
  'Biographical novel',
  'Dying Earth subgenre',
  'Detective fiction',
  'Epistolary novel',
  'Graphic novel',
  'Science fantasy',
  'Urban fiction',
  'Cyberpunk',
  'Novella',
  'Techno-thriller',
  'True crime',
  'Short story',
  'Postmodernism',
  'Supernatural',
  'Hard science fiction',
  'Planetary romance',
  'Popular culture',
  'Biopunk',
  'Marketing',
  'Pastiche',
  'Künstlerroman',
  'American Gothic Fiction',
  'Sports',
  'Existentialism',
  'Music',
  'Fiction',
  'Photography',
  'Psychological novel',
  'Sword and planet',
  'Prose poetry',
  'Role-playing game',
  'Biography',
  'Horror',
  'Medieval romance',
  'Future history',
  'Romance novel',
  'Superhero fiction',
  'Mystery',
  'War novel',
  'Cozy',
  'Naval adventure',
  'Anti-nuclear',
  'Psychology',
  "Boys' school stories",
  'Steampunk',
  'Parallel novel',
  'Comic novel',
  'Western',
  'Conspiracy fiction',
  'Cookbook',
  'Humour',
  'Suspense',
  'Utopian fiction',
  'English public-school stories',
  'Parody',
  'Historical fiction',
  'Contemporary fantasy',
  'Prose',
  'Social commentary',
  'Pornography',
  'Young adult literature',
  'Conspiracy',
  'Fictional crossover',
  'Chivalric romance',
  'Inspirational',
  'Metaphysics',
  'LGBT literature',
  'Essay',
  'Satire',
  'Adventure novel',
  'Play',
  'Field guide',
  'Paranormal romance',
  'Autobiographical comics',
  'Subterranean fiction',
  'Postcyberpunk',
  'School story',
  'Science Fiction',
  'Nature',
  'Alien invasion',
  'Sea story',
  'Dark fantasy',
  'Mathematics',
  'Tragicomedy',
  'Industrial novel',
  'Erotica',
  'Popular science',
  'Non-fiction novel',
  'Comedy',
  'Poetry',
  'Absurdist fiction',
  'History',
  'Hardboiled',
  'Farce',
  'Urban fantasy',
  'Gay novel',
  'Elizabethan romance',
  'Youth',
  'Literary criticism',
  'Chick lit',
  'Western fiction',
  'Locked room mystery',
  'Police procedural',
  'Utopian and dystopian fiction',
  'Computer Science',
  'Thriller',
  'Treatise',
  'Comic science fiction',
  'Sociology',
  'Romantic comedy',
  'Historical romance',
  'Anti-war',
  'Lost World',
  'Fantastique',
  'Comic fantasy',
  'Autobiography',
  'Robinsonade',
  'High fantasy',
  'Space opera',
  'Religious text',
  'Anthology',
  'Education',
  'Social sciences',
  'Low fantasy',
  'Juvenile fantasy',
  'Light novel',
  'Memoir',
  'Science',
  'Social novel',
  'Black comedy',
  'Magic realism',
  'Autobiographical novel',
  'Personal journal',
  'Self-help',
  'Ghost story',
];

const db = drizzle(connection);

const runMigration = async () => {
  // This will run migrations on the database, skipping the ones already applied

  const items = initial_genres.map(g => ({
    id: slugify(g),
    genre: g
  }))

  await db.insert(genres).values(items);

  // Don't forget to close the connection, otherwise the script will hang
  await connection.end();
};
runMigration().then((r) => {
  console.log('seeding succeeded');
});
