name: Test WriteMe App
on:
  push:
    branches:
      - dev
    paths:
      - "apps/writeme/**"
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node Install
        uses:  actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: PNPM Install
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      # - name: Run Linting
      #   run: pnpm exec nx run writeme:lint
      - name: Run Unit Test
        run: pnpm exec nx run writeme:test
      # - name: Run E2E Tests
      #   run: pnpm exec nx run writeme-e2e:e2e-ci
